// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwR-FR0vPVXPlrv58T3jSkkGP7tuoqtJk',
    appId: '1:253894091046:web:2df85d52defa1bb9e161e7',
    messagingSenderId: '253894091046',
    projectId: 'studio-reservation-app',
    authDomain: 'studio-reservation-app.firebaseapp.com',
    databaseURL: 'https://studio-reservation-app-default-rtdb.firebaseio.com',
    storageBucket: 'studio-reservation-app.appspot.com',
    measurementId: 'G-7KEMXFCZ4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkacGQHrB1j4rYSa6xzqjNNfj3uNXr7c',
    appId: '1:253894091046:android:689a75c2e62c8c65e161e7',
    messagingSenderId: '253894091046',
    projectId: 'studio-reservation-app',
    databaseURL: 'https://studio-reservation-app-default-rtdb.firebaseio.com',
    storageBucket: 'studio-reservation-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6jGViWtoHuk3vHyVjUhrEc36jZQYhzec',
    appId: '1:253894091046:ios:d45bd44d0d9a2f13e161e7',
    messagingSenderId: '253894091046',
    projectId: 'studio-reservation-app',
    databaseURL: 'https://studio-reservation-app-default-rtdb.firebaseio.com',
    storageBucket: 'studio-reservation-app.appspot.com',
    iosClientId:
        '253894091046-s442e10212njabc7a3qcgqem2g9v4lun.apps.googleusercontent.com',
    iosBundleId: 'com.example.studioReservationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6jGViWtoHuk3vHyVjUhrEc36jZQYhzec',
    appId: '1:253894091046:ios:d45bd44d0d9a2f13e161e7',
    messagingSenderId: '253894091046',
    projectId: 'studio-reservation-app',
    databaseURL: 'https://studio-reservation-app-default-rtdb.firebaseio.com',
    storageBucket: 'studio-reservation-app.appspot.com',
    iosClientId:
        '253894091046-s442e10212njabc7a3qcgqem2g9v4lun.apps.googleusercontent.com',
    iosBundleId: 'com.example.studioReservationApp',
  );
}
