import 'package:flutter/material.dart';

/* Rectangle Border
    Autogenerated by FlutLab FTF Generator
  */
class PasswordField extends StatefulWidget {
  PasswordField({
    Key? key,
    required this.controller,
    required this.hint,
  }) : super(key: key);

  final TextEditingController controller;
  final String hint;

  @override
  State<PasswordField> createState() => _PasswordFieldState();
}

class _PasswordFieldState extends State<PasswordField> {
  bool isObscure = true;
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 1,
      child: Container(
        width: 355.0,
        height: 60.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
          border: Border.all(
            width: 1.0,
            color: Theme.of(context).shadowColor,
          ),
        ),
        child: Padding(
          padding: const EdgeInsets.fromLTRB(25, 10, 0, 10),
          child: TextFormField(
              textInputAction: TextInputAction.done,
              obscureText: isObscure,
              controller: widget.controller,
              showCursor: true,
              cursorColor: Theme.of(context).buttonTheme.colorScheme?.onSurface,
              decoration: InputDecoration(
                  hintText: widget.hint,
                  suffixIcon: IconButton(
                    onPressed: () {
                      setState(() {
                        isObscure = !isObscure;
                      });
                    },
                    icon: Icon(
                      isObscure ? Icons.visibility_off : Icons.visibility,
                      color: const Color(0xffFD0C89),
                    ),
                  ),
                  floatingLabelBehavior: FloatingLabelBehavior.always,
                  border: InputBorder.none)),
        ),
      ),
    );
  }
}
