import 'package:flutter/material.dart';

import '../helpers/transform_helper.dart';

/* Rectangle Border
    Autogenerated by FlutLab FTF Generator
  */
class PasswordField extends StatefulWidget {
  const PasswordField({
    Key? key,
    required this.controller,
    required this.hint,
    this.isObscure,
  }) : super(key: key);

  final TextEditingController controller;
  final String hint;
  final bool? isObscure;

  @override
  State<PasswordField> createState() => _PasswordFieldState();
}

class _PasswordFieldState extends State<PasswordField> {
  var _obscureText = true;

  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 1,
      child: Container(
        width: 355.0,
        height: 60.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
          border: Border.all(
            width: 1.0,
            color: const Color.fromARGB(255, 255, 255, 255),
          ),
        ),
        child: Padding(
          padding: const EdgeInsets.fromLTRB(25, 10, 0, 10),
          child: TextFormField(
              style: const TextStyle(color: Colors.white),
              obscureText: widget.isObscure == null ? false : true,
              inputFormatters: const [],
              controller: widget.controller,
              showCursor: true,
              cursorColor: Colors.white,
              keyboardType: TextInputType.visiblePassword,
              decoration: InputDecoration(
                  hintText: widget.hint,
                  hintStyle: TextStyle(
                    color: Colors.white.withOpacity(0.7),
                  ),
                  suffixIcon: GestureDetector(
                    onTap: () {
                      setState(() {
                        _obscureText = !_obscureText;
                      });
                    },
                    child: Icon(
                        _obscureText ? Icons.visibility : Icons.visibility_off),
                  ),
                  floatingLabelBehavior: FloatingLabelBehavior.always,
                  border: InputBorder.none)),
        ),
      ),
    );
  }
}
